### ISSUE TITLE
TypeScript 1.5

### ISSUE THREAD

**Issue by jimthedev** [RedSeal-co/ts-tinkerpop#15]
Hi there. Will this project eventually move to TS 1.5?

**Comment by jimlloyd** [comment]
Yes, we will. I'd say there's a good chance it will happen in the next 30 days. Did you recently move a project from 1.4 to 1.5, or are you starting a new project?

**Comment by jimlloyd** [comment]
@jimthedev I've pushed a [branch](https://github.com/RedSeal-co/ts-tinkerpop/tree/tsc1.5) that uses TS 1.5. We won't merge it to master and publish to npm until we're ready to switch all of our related projects to TS 1.5, but I now think that will happen within a week rather than a month.

**Comment by jimthedev** [comment]
Awesome. I'll have to take a look. Thanks.

**Comment by jimlloyd** [comment]
Merged PR #16.
Published as ts-tinkerpop@1.5.0
