### ISSUE TITLE
External db config?

### ISSUE THREAD

**Issue by jimthedev** [RedSeal-co/ts-tinkerpop#18]
Hi Jim,

Is Neo4j, Titan, etc supported by this module? If so, is there special config needed?

Jim

**Comment by jimlloyd** [comment]
Hi Jim, this module only loads TinkerGraph and the core Tinkerpop libraries. You should be able to also add jars for Neo4j or Titan during your application initialization, and add any other initialization code necessary to configure the backend, and then use the ts-tinkerpop API. You might want to use ts-java to expose Typescript interfaces for Neo4j or Titan.

**Comment by mhfrantz** [comment]
We'll hopefully be trying out Titan via ts-tinkerpop in the next couple of months, so we'll share what we learn.

**Comment by jimthedev** [comment]
@mhfrantz @jimlloyd Fantastic, thanks.
