### ISSUE TITLE
install fails on Unbuntu 12.04

### ISSUE THREAD

**Issue by dangersorus** [RedSeal-co/ts-tinkerpop#7]
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ts-tinkerpop"
npm ERR! node v0.10.37
npm ERR! npm  v2.10.0
npm ERR! code ELIFECYCLE

npm ERR! ts-tinkerpop@1.1.5 install: `make install-maven`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ts-tinkerpop@1.1.5 install script 'make install-maven'.
npm ERR! This is most likely a problem with the ts-tinkerpop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make install-maven
npm ERR! You can get their info via:
npm ERR!     npm owner ls ts-tinkerpop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/node/graphapi_test/npm-debug.log

**Comment by dangersorus** [comment]
Requires Java8 
Installed, $JAVA_HOME set. Compiles and installs.

**Comment by jimlloyd** [comment]
Thanks for reporting @dangersorus. We'll update pom.xml to require Java 1.8, and add a note to the README.md.

**Comment by jimlloyd** [comment]
Java 1.8 now explicitly required as of PR #8. Published as ts-tinkerpop@1.1.6.
